---
- name: Install and configure k3s (single node)
  hosts: Vulner
  become: true
  vars:
    k3s_user: root # change this to your preferred local user

  tasks:
    - name: Download and install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure k3s service is enabled and running
      systemd:
        name: k3s
        state: started
        enabled: true

    - name: Wait for k3s to be ready
      shell: |
        kubectl get nodes --no-headers | grep "Ready"
      register: k3s_ready
      retries: 15
      delay: 10
      until: k3s_ready.rc == 0

    - name: Ensure ~/.kube directory exists
      file:
        path: "/home/{{ k3s_user }}/.kube"
        state: directory
        owner: "{{ k3s_user }}"
        group: "{{ k3s_user }}"
        mode: "0700"

    - name: Copy kubeconfig from remote k3s to user's home
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "/home/{{ k3s_user }}/.kube/config"
        owner: "{{ k3s_user }}"
        group: "{{ k3s_user }}"
        mode: "0600"
        remote_src: yes
