---
- name: Cleanup PostgreSQL fuzz environment
  hosts: Vulner
  become: true
  vars:
    postgres_db: test_vulndb
    postgres_user: vuln_user
  tasks:
    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Drop fuzz table if exists
      become_user: postgres
      shell: |
        psql -d {{ postgres_db }} -c "DROP TABLE IF EXISTS vuln_test;"
      ignore_errors: true

    - name: Drop database
      become_user: postgres
      shell: |
        psql -c "DROP DATABASE IF EXISTS {{ postgres_db }};"
      ignore_errors: true

    - name: Drop database user
      become_user: postgres
      shell: |
        psql -c "DROP USER IF EXISTS {{ postgres_user }};"
      ignore_errors: true

    - name: Confirm cleanup
      become_user: postgres
      shell: |
        echo "Databases:"
        psql -c "\l"
        echo "Users:"
        psql -c "\du"
      register: cleanup_status

    - name: Show cleanup result
      debug:
        msg: "{{ cleanup_status.stdout_lines }}"
