---
- name: Install Shuffle SOAR
  hosts: Strike
  become: true
  vars:
    shuffle_dir: /opt/shuffle
    frontend_port: 22000
    frontend_port_https: 22443
    backend_port: 5001
    outer_hostname: Strike
    shuffle_app_hotload_location: /opt/shuffle-apps
    shuffle_file_location: /opt/shuffle-files
    shuffle_opensearch_password: "shufflepass"

  tasks:
    - name: Ensure Shuffle directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ shuffle_dir }}"
        - "{{ shuffle_app_hotload_location }}"
        - "{{ shuffle_file_location }}"

    - name: Create .env file for Shuffle
      copy:
        dest: "{{ shuffle_dir }}/.env"
        content: |
          FRONTEND_PORT={{ frontend_port }}
          FRONTEND_PORT_HTTPS={{ frontend_port_https }}
          BACKEND_PORT={{ backend_port }}
          BACKEND_HOSTNAME=shuffle-backend
          SHUFFLE_APP_HOTLOAD_LOCATION={{ shuffle_app_hotload_location }}
          SHUFFLE_FILE_LOCATION={{ shuffle_file_location }}
          OUTER_HOSTNAME={{ outer_hostname }}
          SHUFFLE_OPENSEARCH_PASSWORD={{ shuffle_opensearch_password }}

    - name: Create docker-compose.yml
      copy:
        dest: "{{ shuffle_dir }}/docker-compose.yml"
        content: |
          version: "3"
          services:
            frontend:
              image: ghcr.io/shuffle/shuffle-frontend:latest
              container_name: shuffle-frontend
              hostname: shuffle-frontend
              ports:
                - "${FRONTEND_PORT}:80"
                - "${FRONTEND_PORT_HTTPS}:443"
              networks:
                - shuffle
              environment:
                - BACKEND_HOSTNAME=${BACKEND_HOSTNAME}
              restart: unless-stopped
              depends_on:
                - backend
            backend:
              image: ghcr.io/shuffle/shuffle-backend:latest
              container_name: shuffle-backend
              hostname: ${BACKEND_HOSTNAME}
              ports:
                - "${BACKEND_PORT}:5001"
              networks:
                - shuffle
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - ${SHUFFLE_APP_HOTLOAD_LOCATION}:/shuffle-apps:z
                - ${SHUFFLE_FILE_LOCATION}:/shuffle-files:z
              env_file: .env
              restart: unless-stopped
            orborus:
              image: ghcr.io/shuffle/shuffle-orborus:latest
              container_name: shuffle-orborus
              hostname: shuffle-orborus
              networks:
                - shuffle
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
              environment:
                - SHUFFLE_APP_SDK_TIMEOUT=300
                - SHUFFLE_ORBORUS_EXECUTION_CONCURRENCY=7
                - ENVIRONMENT_NAME=Shuffle
                - ORG_ID=Shuffle
                - BASE_URL=http://${OUTER_HOSTNAME}:5001
                - DOCKER_API_VERSION=1.40
                - SHUFFLE_STATS_DISABLED=true
                - SHUFFLE_LOGS_DISABLED=true
                - SHUFFLE_SWARM_CONFIG=run
                - CLEANUP=false
                - SHUFFLE_WORKER_IMAGE=ghcr.io/shuffle/shuffle-worker:latest
              env_file: .env
              restart: unless-stopped
              security_opt:
                - seccomp:unconfined
            opensearch:
              image: opensearchproject/opensearch:3.2.0
              hostname: shuffle-opensearch
              container_name: shuffle-opensearch
              environment:
                - "OPENSEARCH_JAVA_OPTS=-Xms3072m -Xmx3072m"
                - bootstrap.memory_lock=true
                - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
                - cluster.initial_master_nodes=shuffle-opensearch
                - cluster.routing.allocation.disk.threshold_enabled=false
                - cluster.name=shuffle-cluster
                - node.name=shuffle-opensearch
                - node.store.allow_mmap=false
                - discovery.seed_hosts=shuffle-opensearch
                - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${SHUFFLE_OPENSEARCH_PASSWORD}
              ulimits:
                memlock:
                  soft: -1
                  hard: -1
                nofile:
                  soft: 65536
                  hard: 65536
              volumes:
                - shuffle-database:/usr/share/opensearch/data:z
              ports:
                - 9200:9200
              networks:
                - shuffle
              restart: unless-stopped

          volumes:
            shuffle-database:
              driver: local

          networks:
            shuffle:
              driver: bridge

    - name: Start Shuffle containers
      command: docker-compose -f "{{ shuffle_dir }}/docker-compose.yml" up -d
      args:
        chdir: "{{ shuffle_dir }}"

    - name: Display access info
      debug:
        msg: "Shuffle frontend is accessible at http://{{ outer_hostname }}:{{ frontend_port }} and backend at http://{{ outer_hostname }}:{{ backend_port }}"
