- name: Remove SonarQube
  hosts: Strike
  become: true
  tasks:
    - name: Stop and remove SonarQube containers
      command: docker compose -f /opt/sonarqube/docker-compose.yml down
      ignore_errors: true

    - name: Remove SonarQube directory
      file:
        path: /opt/sonarqube
        state: absent

    - name: Remove SonarQube Docker image
      command: docker rmi sonarqube:latest
      ignore_errors: true

    - name: Prune unused Docker volumes
      command: docker volume prune -f
      ignore_errors: true
