- name: Install Trivy in Docker on Strike
  hosts: Strike
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Pull Trivy Docker image
      command: docker pull aquasec/trivy:latest

    - name: Create alias script for Trivy
      copy:
        dest: /usr/local/bin/trivy
        mode: "0755"
        content: |
          #!/bin/bash
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.cache:/root/.cache \
            aquasec/trivy:latest "$@"

    - name: Verify Trivy installation
      command: trivy --version
      register: trivy_version

    - name: Show installed Trivy version
      debug:
        var: trivy_version.stdout
