- name: Remove Dockerized Trivy from Strike
  hosts: Strike
  become: true
  tasks:
    - name: Remove Trivy alias script
      file:
        path: /usr/local/bin/trivy
        state: absent

    - name: Remove Trivy Docker image
      command: docker rmi -f aquasec/trivy:latest
      ignore_errors: true

    - name: Remove Trivy cache directory
      file:
        path: "{{ ansible_env.HOME }}/.cache"
        state: absent
